apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-sync-push
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-cloud-secret-store
    kind: ClusterSecretStore
  target:
    name: git-sync-push
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: git-sync-push
