apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: google-cloud-secret-store
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: tailscale-operator
