apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sgrbot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-secret-store
    kind: ClusterSecretStore
  target:
    name: sgrbot
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: name:sgrbot
