apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lavalink
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-cloud-secret-store
    kind: ClusterSecretStore
  target:
    name: lavalink
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: lavalink
