apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: google-cloud-secret-store
spec:
  provider:
    gcpsm:
      projectID: sglre6355
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: google-cloud-secret-manager
            key: secret-access-credentials
            namespace: external-secrets
