apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: scaleway-secret-store
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: f21584a1-3f08-433e-b105-3587b30aca99
      accessKey:
        secretRef:
          name: scaleway-secret-manager
          namespace: external-secrets
          key: access-key
      secretKey:
        secretRef:
          name: scaleway-secret-manager
          namespace: external-secrets
          key: secret-access-key
