apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: daily-chinese-teacher
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-cloud-secret-store
    kind: ClusterSecretStore
  target:
    name: daily-chinese-teacher
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: daily-chinese-teacher
