apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zensur
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-cloud-secret-store
    kind: ClusterSecretStore
  target:
    name: zensur
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: zensur
