apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-secret-store
    kind: ClusterSecretStore
  target:
    name: minecraft-server
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: name:minecraft-server
